// Helps by having only one file in which to refer to a list of all the possible
// actions for app
REGISTER_REQUEST: 'REGISTER_REQUEST';
REGISTER_SUCCESS: 'REGISTER_SUCCESS';
REGISTER_FAILURE: 'REGISTER_FAILURE';

LOGIN_REQUEST: 'LOGIN_REQUEST';
LOGIN_SUCCESS: 'LOGIN_SUCCESS';
LOGIN_FAILURE: 'LOGIN_FAILURE';

LOGOUT: 'LOGOUT';